id: P62393212
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA30014
  instance_id: http://purl.bdrc.io/resource/IE30014
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ལམ་རིམ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1844
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    76dff7f1cc514779961175b5360f6589:
      title: པོད ༡་ལམ་རིམ
      volume_number: 1
      base_file: UT30014_5747_0000.txt
      reference: http://purl.bdrc.io/resource/VL003D68DC5B812802
      image_group: '5747'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW30014
  - http://purl.bdrc.io/resource/W30014
  ocr_software: Namsel
created_at: '2021-12-22T11:15:21.180442'
last_modified_at: '2021-12-22T11:15:21.180449'
